server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  # SPA fallback: deep links /events/:id no dan 404
  location / {
    try_files $uri $uri/ /index.html;
  }

  # Cache estáticos de Vite
  location /assets/ {
    expires 1y;
    add_header Cache-Control "public, immutable";
  }
}
